version: '3.8'

services:
  server:
    build:
      context: .
      target: final
      args:
        RAILWAY_SERVICE_ID: ${RAILWAY_SERVICE_ID}
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    container_name: ndclasses-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: name-postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: